
export enum AspectType {
    CONJUNCTION = 'CONJUNCTION',
    OPPOSITION = 'OPPOSITION',
    TRIGON = 'TRIGON',
    SEXTILE = 'SEXTILE',
    SEMI_SEXTILE = 'SEMI_SEXTILE',
    KWINKUS = 'KWINKUS',
    SQUARE = 'SQUARE',
    SQUARE_HALF = 'SQUARE_HALF'
}